### ISSUE TITLE
[Feat]: Allow setting severity level that reviewer app will reopen

### ISSUE THREAD

**Issue by linus345** [advanced-security/ghas-reviewer-app#89]
### What new feature are you looking for / expect?

Currently the severities that the Reviewer app will reopen findings for [is a static list](https://github.com/advanced-security/ghas-reviewer-app/blob/96c66f0f4577a98a19b1019b27c33b13394ee332/ghasreview/setup.py#L105) set to:
```python
"GHAS_SEVERITIES": ["critical", "high", "error", "errors"],
```

We want this to be configurable to be more strict. Passing in no values should ideally reopen all findings, no matter the severity level.

Another thing relating to severities that we've seen is that a finding that shows `high` severity in the UI (see screenshot) might not actually be treated as a high severity by the reviewer app. This looks to be because of the reviewer app using `alert.rule.severity` which shows a different (lower in this case) severity level (`"severity": "warning"`), while there's another field `alert.rule.security_severity_level` that shows the severity level as high (`"security_severity_level": "high"`). See json below which is copied from a webhook request where we saw this.

<img width="260" alt="image" src="https://github.com/user-attachments/assets/0f823a5c-a71c-45be-95cc-e3fdf7e93700" />

```json
{
  "action": "closed_by_user",
  "alert": {
    "number": 1,
    "state": "dismissed",
    "dismissed_reason": "false positive",
    "rule": {
      "id": "java/sensitive-log",
      "severity": "warning",
      "description": "Insertion of sensitive information into log files",
      "name": "java/sensitive-log",
      "tags": [
        "external/cwe/cwe-532",
        "security"
      ],
      "full_description": "Writing sensitive information to log files can allow that information to be leaked to an attacker more easily.",
      "help": "# Insertion of sensitive information into log files\nInformation written to log files can be of a sensitive nature and give valuable guidance to an attacker or expose sensitive user information. Third-party logging utilities like Log4J and SLF4J are widely used in Java projects. When sensitive information is written to logs without properly set logging levels, it is accessible to potential attackers who can use it to gain access to file storage.\n\n\n## Recommendation\nDo not write secrets into the log files and enforce proper logging level control.\n\n\n## Example\nThe following example shows two ways of logging sensitive information. In the 'BAD' case, the credentials are simply written to a debug log. In the 'GOOD' case, the credentials are never written to debug logs.\n\n\n```java\npublic static void main(String[] args) {\n    {\n        private static final Logger logger = LogManager.getLogger(SensitiveInfoLog.class);\n\n        String password = \"Pass@0rd\";\n\n        // BAD: user password is written to debug log\n        logger.debug(\"User password is \"+password);\n    }\n\t\n    {\n        private static final Logger logger = LogManager.getLogger(SensitiveInfoLog.class);\n  \n        String password = \"Pass@0rd\";\n\n        // GOOD: user password is never written to debug log\n        logger.debug(\"User password changed\")\n    }\n}\n\n```\n\n## References\n* [OWASP Logging Guide](https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html)\n* Common Weakness Enumeration: [CWE-532](https://cwe.mitre.org/data/definitions/532.html).\n",
      "security_severity_level": "high"
    },
  }
}
```

The end result for this is that a finding that shows severity level `high` in the UI, as in the above screenshot, is still dismissible. Webhook response in this case is:
```json
{"calls":{"onCodeScanningAlertClose":{"message":"Severity is not high enough to get security involved, doing nothing."}},"status":"HIT"}
```

### Expectations

Required / Manditory Feature

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GeekMasher** [comment]
Thanks for reporting this @linus345, I will take a look Monday and see if we can resolve this as soon as possible.

**Comment by GeekMasher** [comment]
We have an open PR with the requested fix. Waiting for review now
https://github.com/advanced-security/ghas-reviewer-app/pull/90

**Comment by linus345** [comment]
Hey, thanks for the quick action!

This partially fixes the issue by allowing us to pass in the severities we want to check. Although we've seen cases where the `severity` field is `warning` while the `security_severity_level` field is `critical` (see screenshot). With [how the code is written today](https://github.com/advanced-security/ghas-reviewer-app/blob/e65181f1f5719f24ccc9e2dc66b8046e6c93bb7a/ghasreview/app.py#L159-L168), it will first look at the `severity` field, and if not part of the severities to consider it will return and not check the alert, without continuing to check the level of `security_severity_level`.

What we think should happen instead is that both should be considered, and the one with the highest severity should be prioritized. In the above example we want the finding to be reopened since `security_severity_level` is `critical`, and not for it to be skipped just because the `severity` field says `warning` but it will never check `security_severity_level` if we don't specify `warning` in the new flag, because then it returns early.

![image](https://github.com/user-attachments/assets/6ba41860-fd3d-4323-aec2-3b1072079e62)

**Comment by linus345** [comment]
It would be great if this works the same way that code scanning / security alerts work which is described [here](https://docs.github.com/en/code-security/code-scanning/managing-code-scanning-alerts/about-code-scanning-alerts#about-alert-severity-and-security-severity-levels):

> The severity level for a code scanning alert indicates how much risk the problem adds to your codebase.

> Severity. All code scanning alerts have a level of Error, Warning, or Note.
Security severity. Each security alert found using CodeQL also has a security severity level of Critical, High, Medium, or Low.
**When an alert has a security severity level, code scanning displays and uses this level in preference to the severity.** Security severity levels follow the industry-standard Common Vulnerability Scoring System (CVSS) that is also used for advisories in the GitHub Advisory Database. For more information, see [CVSS: Qualitative Severity Rating Scale](https://www.first.org/cvss/v3.1/specification-document#Qualitative-Severity-Rating-Scale).
